Repository tomriddle77/Hacktober22, pull requests merged in 2022-10, with the labels that each got.

#5 Create TicTacToe.py
  Python/TicTacToe.py
Labels: enhancement, hacktoberfest-accepted

#9 Added Searching Algorithms (in C++)
  C++ algos/Searching Algos/InterpolationSearch.cpp
  C++ algos/Searching Algos/IterativeBinarySearch.cpp
  C++ algos/Searching Algos/JumpSearch.cpp
  C++ algos/Searching Algos/LinearSearch.cpp
  C++ algos/Searching Algos/RecursiveBinarySearch.cpp
  Contributer.md
Labels: enhancement, hacktoberfest2022, approved

#22 Update README.md
  README.md
Labels: good first issue, hacktoberfest-accepted, approved

#20 Create Gradient Descent.py
  Data Science Project/Gradient Descent.py
Labels: hacktoberfest-accepted, hacktoberfest2022, approved

#15 Create Type_of_Triangle.py
  Contributer.md
  Python/Type_of_Triangle.py
Labels: good first issue, hacktoberfest-accepted, approved

#44 Added logistic regression cost function code.
  Contributer.md
  Data Science Project/LogisticRegression.py
Labels: enhancement, approved

#36 Random Password Generator
  Contributer.md
  Python/RandomPasswordGenerator.py
Labels: hacktoberfest2022, approved

#33 Created words list for hangman.py
  Python/hangmanwords.py
Labels: enhancement, question

#54 adding sudoku solver
  Python/sudokusolver.py
Labels: hacktoberfest-accepted, approved

#83 Update Contributer.md
  Contributer.md
  Python/Fibonacci.py
Labels: hacktoberfest-accepted, approved

#84 Update Contributer.md
  Contributer.md
Labels: good first issue, hacktoberfest-accepted, approved

#255 bubble sort using c++
  C++ algos/Sorting Algos/bubble sort using c++
Labels: hacktoberfest-accepted, hacktoberfest2022

#212 Logistic Regression with Gradient Descent in JS
  Contributer.md
  Data Science Project/Calculator.py
  Data Science Project/LogisticRegressionWithGradientDescent.js
  java/Sorting Algo/CyclicSort.java
Labels: hacktoberfest-accepted, hacktoberfest2022, approved
